federation_version: =2.5.4

subgraphs:
  users:
    routing_url: http://localhost:4001/ # graphql-users.dev.svc.cluster.local
    schema:
      base: .
      file: '../../../../graphql/users/src/schema.graphql'
      graphref: codyslexia@dev
      subgraph: users
      subgraph_url: http://localhost:4001/ # graphql-users.dev.svc.cluster.local
    request:
      - insert:
          name: 'Router-Authorization'
          value: env.USERS_SUBGRAPH_SECRET

  projects:
    routing_url: http://localhost:4002/ # graphql-proejcts.dev.svc.cluster.local
    schema:
      base: .
      file: '../../../../graphql/projects/src/schema.graphql'
      graphref: codyslexia@dev
      subgraph: projects
      subgraph_url: http://localhost:4002/ # graphql-projects.dev.svc.cluster.local
    request:
      - insert:
          name: 'Router-Authorization'
          value: env.PROJECTS_SUBGRAPH_SECRET

headers:
  all:
    request:
      - propagate:
        named: 'Router-Authorization'
  subgraphs:
    users:
      request:
        - insert:
            name: 'Router-Authorization'
            value: env.USERS_SUBGRAPH_SECRET
    projects:
      request:
        - insert:
            name: 'Router-Authorization'
            value: env.PROJECTS_SUBGRAPH_SECRET

cors:
  allow_any_origin: false
  origins:
    - https://studio.apollographql.com
    - https://nexa.codyslexia.com
    - http://localhost:4000
    - http://localhost:4001
    - http://localhost:4002
