federation_version: =2.5.4

subgraphs:
  users:
    routing_url: http://graphql-users.dev.svc.cluster.local
    schema:
      base: .
      file: '../../../../graphql/users/src/schema.graphql'
      graphref: codyslexia@local
      subgraph: users
      subgraph_url: http://graphql-users.dev.svc.cluster.local
    request:
      - insert:
          name: 'Router-Authorization'
          value: env.USERS_SUBGRAPH_SECRET

  projects:
    routing_url: http://graphql-projects.dev.svc.cluster.local
    schema:
      base: .
      file: '../../../../graphql/projects/src/schema.graphql'
      graphref: codyslexia@local
      subgraph: projects
      subgraph_url: http://graphql-projects.dev.svc.cluster.local
    request:
      - insert:
          name: 'Router-Authorization'
          value: env.PROJECTS_SUBGRAPH_SECRET

headers:
  all:
    request:
      - propagate:
        named: 'Router-Authorization'
  subgraphs:
    users:
      request:
        - insert:
            name: 'Router-Authorization'
            value: env.USERS_SUBGRAPH_SECRET
    projects:
      request:
        - insert:
            name: 'Router-Authorization'
            value: env.PROJECTS_SUBGRAPH_SECRET

cors:
  allow_any_origin: true
  origins:
    # - https://studio.apollographql.com
    # - https://nexa.codyslexia.com
    # - http://localhost:4000
    # - http://localhost:4001
    # - http://localhost:4002
