# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

---
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: codyslexia
requires:
  - configs: ['stack-core']
    path: ./tools/skaffold/src/stack/stack.yaml
profiles:
  - name: dev
    activation:
      - command: dev
      - kubeContext: docker-desktop
    requiresAllActivations: true
    manifests:
      rawYaml:
        - '.nexa/apps/**/**/k8s'
      kustomize:
        buildArgs: []
        paths:
          # - '.nexa/skaffold/dev' # ?
          - 'tools/kustomize/src/overlays/dev'
    deploy:
      kubeContext: docker-desktop
      kubectl:
        defaultNamespace: dev
        remoteManifests:
          - './tools/kustomize/src/overlays/dev'
      helm: {}
    build:
      local:
        concurrency: 1
        push: false
        useDockerCLI: true
      tagPolicy:
        sha256: {}
      artifacts:
        # Faker API
        - image: ghcr.io/codyslexia/faker-api
          context: .
          docker:
            dockerfile: .nexa/apps/services/faker-api/Dockerfile
        # Go API
        - image: ghcr.io/codyslexia/goapi
          context: .
          docker:
            dockerfile: apps/backend/goapi/Dockerfile
        # QRCode API
        - image: ghcr.io/codyslexia/qrcode-api
          context: .
          docker:
            dockerfile: .nexa/apps/services/qrcode-api/Dockerfile
        # Rust API
        - image: ghcr.io/codyslexia/rustapi
          context: apps/backend/rustapi
          docker:
            dockerfile: apps/backend/rustapi/Dockerfile
        # TOTP API
        - image: ghcr.io/codyslexia/totp-api
          context: .
          docker:
            dockerfile: .nexa/apps/services/totp-api/Dockerfile
        # Frontend
        - image: ghcr.io/codyslexia/frontend-web
          context: .
          docker:
            dockerfile: apps/frontend/web/Dockerfile
