---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-projects
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codyslexia
      system: graphql-federation
      component: graphql-projects
  template:
    metadata:
      labels:
        app: codyslexia
        system: graphql-federation
        component: graphql-projects
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
        - name: graphql-projects
          image: ghcr.io/codyslexia/graphql-projects
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - secretRef:
                name: graphql-projects-secret
          resources:
            requests:
              memory: '640M'
              cpu: '100m'
            limits:
              memory: '1000M'
              cpu: '1000m'
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-projects
  namespace: dev
  labels:
    app: codyslexia
    component: graphql-projects
spec:
  selector:
    app: codyslexia
    component: graphql-projects
  ports:
    - name: graphql-projects
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-projects-autoscaler
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphql-projects
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Secret
metadata:
  name: graphql-projects-secret
  namespace: dev
type: Opaque
data:
  graphql-projects-credentials.json: |
    $BASE64_ENCODED_JSON_CONTENT
