# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

---
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: cert-manager
deploy:
  helm:
    releases:
      - name: cert-manager
        namespace: nexa
        createNamespace: true
        remoteChart: jetstack/cert-manager
        setValues:
          installCRDs: true
          prometheus.enabled: true
          extraArgs: '{--feature-gates=AdditionalCertificateOutputFormats=true,ExperimentalGatewayAPISupport=true}'
