# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

---
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: prometheus-operator
deploy:
  helm:
    releases:
      - name: prometheus-operator
        namespace: monitoring
        createNamespace: true
        remoteChart: prometheus-community/kube-prometheus-stack
