/**
 * Copyright (c) 2023-2024 Codyslexia
 * @license MIT
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* eslint-disable @typescript-eslint/no-unused-vars */
import { faker } from '@faker-js/faker'
import { tuple } from '@shared/core'

export const fakerModules = tuple(
  'address',
  'animal',
  'color',
  'commerce',
  'company',
  'database',
  'datatype',
  'date',
  'finance',
  'git',
  'hacker',
  'image',
  'internet',
  'lorem',
  'music',
  'name',
  'phone',
  'random',
  'science',
  'system',
  'vehicle',
  'word'
)

export type FakerModules = (typeof fakerModules)[number]

const FAKER_APIS = [
  {
    module: 'address',
    options: {
      buildingNumber: null,
      city: null,
      cityName: null,
      cityPrefix: null,
      citySuffix: null,
      country: null,
      county: null,
      latitude: null,
      longitude: null,
      secondaryAddress: null,
      state: null,
      stateAbbr: null,
      streetAddress: null,
      streetName: null,
      streetSuffix: null,
      zipCode: null,
      zipCodeByState: null,
    },
  },
  {
    module: 'commerce',
    options: {
      color: null,
      department: null,
      productName: null,
      price: null,
      productAdjective: null,
      productMaterial: null,
      product: null,
    },
  },
  {
    module: 'company',
    options: {
      adjective: null,
      bs: null,
      catchPhrase: null,
      industry: null,
      logo: null,
      name: null,
      suffixes: null,
      companyName: null,
      jobArea: null,
      jobDescriptor: null,
      jobTitle: null,
    },
  },
  {
    module: 'phone',
    options: {
      imei: null,
      phoneNumber: null,
      phoneNumberFormat: null,
      phoneFormats: null,
    },
  },
  {
    module: 'date',
    options: {
      between: { from: null, to: null },
      future: null,
      month: { abbr: null, context: null },
      past: null,
      recent: null,
      soon: null,
      weekday: { abbr: null, context: null },
      year: { min: null, max: null },
    },
  },
  {
    module: 'finance',
    options: {
      account: null,
      accountName: null,
      amount: { min: null, max: null, precision: null },
      bic: null,
      bitcoinAddress: null,
      creditCardCVV: null,
      creditCardNumber: null,
      creditCardType: null,
      currencyCode: null,
      currencyName: null,
      currencySymbol: null,
      iban: null,
      mask: null,
      transactionType: null,
    },
  },
  {
    module: 'git',
    options: {
      branch: null,
      commitEntry: null,
      commitMessage: null,
      commitSha: null,
      shortSha: null,
    },
  },
  {
    module: 'hacker',
    options: {
      abbreviation: null,
      adjective: null,
      noun: null,
      verb: null,
      ingverb: null,
      phrase: null,
    },
  },
  {
    module: 'image',
    options: {
      abstract: null,
      animals: null,
      avatar: { protocol: null },
      business: null,
      cats: null,
      city: null,
      dataUri: null,
      fashion: null,
      food: null,
      image: { category: null, width: null, height: null },
      imageUrl: { category: null, width: null, height: null },
      nature: null,
      people: null,
      sports: null,
      technics: null,
      transport: null,
    },
  },
  {
    module: 'internet',
    options: {
      avatar: null,
      domainName: null,
      email: null,
      exampleEmail: null,
      ip: null,
      ipv6: null,
      mac: null,
      password: null,
      protocol: null,
      url: null,
      userAgent: null,
      userName: null,
    },
  },
  {
    module: 'lorem',
    options: {
      lines: null,
      paragraphs: null,
      sentence: { words: null },
      sentences: null,
      slug: null,
      text: null,
      words: null,
    },
  },
  {
    module: 'name',
    options: {
      firstName: null,
      lastName: null,
      findName: null,
      jobArea: null,
      jobDescriptor: null,
      jobTitle: null,
      prefix: null,
      suffix: null,
      title: null,
    },
  },
  {
    module: 'random',
    options: {
      alpha: null,
      alphaNumeric: null,
      boolean: null,
      float: { min: null, max: null, precision: null },
      hexaDecimal: null,
      number: { min: null, max: null, precision: null },
      objectElement: null,
      uuid: null,
    },
  },
  {
    module: 'system',
    options: {
      commonFileExt: null,
      commonFileName: null,
      commonFileType: null,
      directoryPath: null,
      filePath: null,
      fileName: null,
      fileType: null,
      mimeType: null,
      semver: null,
    },
  },
]
