# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - '../../base'
  - './api-ingress.yaml'
  - './web-ingress.yaml'

labels:
  - pairs:
      app: codyslexia

patches:
  - target:
      kind: ClusterIssuer
      name: cluster-issuer
    patch: |-
      - op: replace
        path: /spec/acme/server
        value: https://acme-staging-v02.api.letsencrypt.org/directory
  - target:
      kind: Certificate
      name: server-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: '*.dev.svc.cluster.local'
      - op: replace
        path: /spec/dnsNames/0
        value: '*.dev.svc'
  - target:
      kind: Certificate
      name: mongo-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: '*.mongodb.dev.svc.cluster.local'
      - op: replace
        path: /spec/dnsNames/0
        value: 'mongodb.dev.svc'
  - target:
      kind: Certificate
      name: client-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: '*.dev.svc.cluster.local'
      - op: replace
        path: /spec/dnsNames/0
        value: '*.dev.svc'
  - target:
      kind: Certificate
      name: nats-server-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/0
        value: nats
      - op: replace
        path: /spec/dnsNames/1
        value: nats.dev
      - op: replace
        path: /spec/dnsNames/2
        value: nats.dev.svc
      - op: replace
        path: /spec/dnsNames/3
        value: nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/4
        value: '*.nats'
      - op: replace
        path: /spec/dnsNames/5
        value: '*.nats.dev'
      - op: replace
        path: /spec/dnsNames/6
        value: '*.nats.dev.svc'
      - op: replace
        path: /spec/dnsNames/7
        value: nats-0.nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/8
        value: nats-1.nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/9
        value: nats-2.nats.dev.svc.cluster.local
  - target:
      kind: Certificate
      name: nats-client-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/0
        value: nats
      - op: replace
        path: /spec/dnsNames/1
        value: nats.dev
      - op: replace
        path: /spec/dnsNames/2
        value: nats.dev.svc
      - op: replace
        path: /spec/dnsNames/3
        value: nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/4
        value: '*.nats'
      - op: replace
        path: /spec/dnsNames/5
        value: '*.nats.dev'
      - op: replace
        path: /spec/dnsNames/6
        value: '*.nats.dev.svc'
      - op: replace
        path: /spec/dnsNames/7
        value: nats-0.nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/8
        value: nats-1.nats.dev.svc.cluster.local
      - op: replace
        path: /spec/dnsNames/9
        value: nats-2.nats.dev.svc.cluster.local
  - target:
      kind: ClusterRoleBinding
      name: nats-server-binding
      namespace: dev
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: dev
