# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: nexa
  labels:
    app: codyslexia
    component: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: codyslexia
    component: mongodb
