# Copyright (c) 2023-2024 Codyslexia
# @license MIT
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Unmergeable Labels Check

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge:
    if: ${{ github.repository_owner == 'codyslexia' }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "${{ toJSON(github.event.*.labels.*.name) }}"
          node -e 'const forbidden = ["target: next major version", "status: needs tests", "status: in-progress", "blocked: needs rebase", "status: do not merge"];
           const match = ${{ toJSON(github.event.*.labels.*.name) }}.find(l => forbidden.includes(l.toLowerCase()));
           if (match) {
            console.log("❌ Cannot merge PRs that are labeled with " + match);
            process.exit(1)
           }'
